apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: git-basic-auth-ext
spec:
  secretStoreRef:
    name: vault-backend   
    kind: ClusterSecretStore
    refreshInterval: "1h"
  target:
    name: git-basic-auth
    template:
      type: kubernetes.io/basic-auth
      engineVersion: v2
      metadata:
        annotations:
          tekton.dev/git-0: https://github.com
      data:
        username: "{{ .user }}"
        password: "{{ .password }}"

  data:
    - secretKey: user
      remoteRef:
        key: projeto-poc/git-basic-auth
        property: user

    - secretKey: password
      remoteRef:
        key: projeto-poc/git-basic-auth
        property: password