apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: multiplas-etapas-com-script
spec:
  steps:
    - name: primeira
      image: registry.access.redhat.com/ubi8/ubi-minimal
      command:
        - /bin/bash
        - -c
        - echo "Primeira Etapa executando"

    - name: segunda
      image: registry.access.redhat.com/ubi8/ubi-minimal
      command:
        - /bin/bash
        - -c
        - echo "Segunda Etapa executando"

    - name: terceira-com-script
      image: registry.access.redhat.com/ubi8/ubi
      script: |
        #!/usr/bin/env bash
        
        echo "#### Installando tools ####"

        dnf install iputils -y

        echo "#### Executando ping ####"

        ping redhat.com -c 5

        echo "### Finalizando a terceira etapa ###"
