apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: primeira-task
spec:
  steps:
    - name: start
      image: registry.access.redhat.com/ubi8/ubi-minimal
      command:
        - /bin/bash
      args: ['-c', 'echo "Hello World"']