# Para que esse exemplo funcione, é necessário criar a secret git-basic-auth com as chaves username e password
# oc apply -f tekton/overview/tasks/task-ler-secret.yaml -n empresa-cicd && tkn task start ler-secret -n empresa-cicd --showlog
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ler-secret
spec:
  steps:
    - name: imprimir-cores-do-configmap
      image: registry.access.redhat.com/ubi8/ubi
      env:
        - name: GITUSER
          valueFrom:
            secretKeyRef:
              name: git-basic-auth
              key: username
        - name: GITPASSWORD
          valueFrom:
            secretKeyRef:
              name: git-basic-auth
              key: password
      script: |
        
        echo "#### Exect git clone ####"
        
        echo $GITUSER
        echo $GITPASSWORD
